"""Multi-blog Indonesian coupon aggregator (sample) — represent semua sumber RSS/blog.

Untuk production: tambah RSS parsing untuk blog kupon Indonesia populer (idkupon.com,
diskon.com, kuponseger.id, dll). V1 mock realistis ditampilkan di sini.
"""
from app.scrapers._factory import make_promo_scraper, days_from_now


_BLOG_DATA = [
    {
        "code": "AHHA50",
        "title": "Tokopedia — Diskon 50rb Pengguna Baru AHHA",
        "description": "Voucher hanya untuk akun baru daftar di Tokopedia. Min belanja Rp 200.000.",
        "discount_type": "fixed",
        "discount_value": 50000,
        "min_spend": 200000,
        "category_slug": "ecommerce",
        "expires_at": days_from_now(25),
        "merchant_slug": "tokopedia",
    },
    {
        "code": "ZALORA20",
        "title": "Zalora — Diskon 20% Fashion Pria",
        "description": "Min belanja Rp 300.000. Berlaku semua brand fashion pria.",
        "discount_type": "percent",
        "discount_value": 20,
        "min_spend": 300000,
        "max_discount": 100000,
        "category_slug": "fashion",
        "expires_at": days_from_now(15),
        "merchant_slug": "zalora",
    },
    {
        "code": "FASHION55",
        "title": "Zalora — Diskon 55% Koleksi Wanita Akhir Musim",
        "description": "Diskon flat 55% untuk koleksi pakaian wanita akhir musim. Min belanja Rp 250.000.",
        "discount_type": "percent",
        "discount_value": 55,
        "min_spend": 250000,
        "max_discount": 200000,
        "category_slug": "fashion",
        "expires_at": days_from_now(7),
        "merchant_slug": "zalora",
    },
    {
        "code": "SHOPEEFASHION70",
        "title": "Shopee Fashion — Diskon 70% Brand Lokal",
        "description": "Flash sale fashion lokal Shopee Mall. Min belanja Rp 100.000.",
        "discount_type": "percent",
        "discount_value": 70,
        "min_spend": 100000,
        "max_discount": 150000,
        "category_slug": "fashion",
        "expires_at": days_from_now(3),
        "merchant_slug": "shopee",
    },
    {
        "code": "SHOPEECB30",
        "title": "Shopee — Cashback 30% Voucher ShopeePay",
        "description": "Cashback ShopeePay 30% max Rp 30.000 untuk semua kategori. Min belanja Rp 75.000.",
        "discount_type": "cashback",
        "discount_value": 30,
        "min_spend": 75000,
        "max_discount": 30000,
        "category_slug": "ecommerce",
        "expires_at": days_from_now(10),
        "merchant_slug": "shopee",
    },
    {
        "code": "TOKOPEDIACB",
        "title": "Tokopedia — Cashback Rp 40.000 GoPay",
        "description": "Cashback ke GoPay Coins. Min belanja Rp 150.000.",
        "discount_type": "cashback",
        "discount_value": 40000,
        "min_spend": 150000,
        "category_slug": "ecommerce",
        "expires_at": days_from_now(14),
        "merchant_slug": "tokopedia",
    },
    {
        "code": "LAZADAGAJIAN",
        "title": "Lazada Gajian — Cashback Rp 75.000",
        "description": "Promo gajian tanggal muda. Min belanja Rp 300.000.",
        "discount_type": "cashback",
        "discount_value": 75000,
        "min_spend": 300000,
        "category_slug": "ecommerce",
        "expires_at": days_from_now(5),
        "merchant_slug": "lazada",
    },
    {
        "code": "BLIBLI10K",
        "title": "Blibli — Voucher Rp 10.000 Tanpa Min Belanja",
        "description": "Berlaku semua kategori produk. 1x per user per minggu.",
        "discount_type": "fixed",
        "discount_value": 10000,
        "category_slug": "ecommerce",
        "expires_at": days_from_now(12),
        "merchant_slug": "blibli",
    },
    {
        "code": "BUKAGRATIS",
        "title": "Bukalapak — Gratis Ongkir Max Rp 20.000",
        "description": "Min belanja Rp 50.000. Berlaku semua wilayah Indonesia.",
        "discount_type": "free_shipping",
        "discount_value": 0,
        "min_spend": 50000,
        "max_discount": 20000,
        "category_slug": "ecommerce",
        "expires_at": days_from_now(18),
        "merchant_slug": "bukalapak",
    },
]


MultiBlogScraper = make_promo_scraper(
    target_id="multi_blog_aggregator",
    merchant_slug="multi",
    name="Multi Blog Aggregator (Indonesian)",
    url="https://www.kupondiskon.com/",
    mock_data=_BLOG_DATA,
    interval_minutes=120,
)
