"""Generate single SQL file untuk paste di Supabase SQL Editor.

Fetches semua data dari production API (Railway), bikin file:
  scripts/supabase_migration.sql

Yang berisi:
1. CREATE TABLE (Postgres syntax) — merchants, categories, coupons, scrape_logs, coupon_votes
2. CREATE INDEX (semua, termasuk GIN trigram via pg_trgm)
3. INSERT data dari production
4. SELECT setval untuk reset sequences

Output file siap di-paste di Supabase Studio → SQL Editor → Run.
"""
from __future__ import annotations

import json
import sys
import urllib.request
from pathlib import Path

PROD_API = "https://superkupon-backend-production.up.railway.app"
ADMIN_KEY = "TOH_-mM858tjDmorSiNmOzwRrghyODKEgZBhyUIkg6I"
OUT = Path(__file__).parent / "supabase_migration.sql"


def fetch_json(path: str, headers: dict | None = None) -> list | dict:
    req = urllib.request.Request(f"{PROD_API}{path}", headers=headers or {})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())


def sql_escape(v):
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v).replace("'", "''")
    return f"'{s}'"


def sql_row(values: list) -> str:
    return "(" + ", ".join(sql_escape(v) for v in values) + ")"


def main():
    print("Fetching production data...")

    merchants = fetch_json("/merchants")
    print(f"  ✓ merchants: {len(merchants)}")

    categories = fetch_json("/categories")
    print(f"  ✓ categories: {len(categories)}")

    coupons = fetch_json("/coupons?limit=200")
    print(f"  ✓ coupons: {len(coupons)}")

    logs = fetch_json(
        "/admin/scrape-logs?limit=500",
        headers={"X-API-Key": ADMIN_KEY},
    )
    print(f"  ✓ scrape_logs: {len(logs)}")

    print("\nGenerating SQL...")
    parts = []

    # ===== Header =====
    parts.append("""-- ============================================================
-- SuperKupon Backup Migration to Supabase
-- Generated by scripts/generate_supabase_sql.py
-- Paste this in Supabase Studio → SQL Editor → Run
-- ============================================================

-- Enable pg_trgm extension for fuzzy search (similarity, %)
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ============================================================
-- TABLES (drop + recreate untuk clean slate)
-- ============================================================

DROP TABLE IF EXISTS coupon_votes CASCADE;
DROP TABLE IF EXISTS coupons CASCADE;
DROP TABLE IF EXISTS scrape_logs CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS merchants CASCADE;
DROP TABLE IF EXISTS alembic_version CASCADE;

CREATE TABLE merchants (
    id SERIAL PRIMARY KEY,
    slug VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    logo_url VARCHAR(512),
    website VARCHAR(512)
);
CREATE UNIQUE INDEX ix_merchants_slug ON merchants (slug);

CREATE TABLE categories (
    id SERIAL PRIMARY KEY,
    slug VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    icon VARCHAR(64)
);
CREATE UNIQUE INDEX ix_categories_slug ON categories (slug);

CREATE TABLE coupons (
    id SERIAL PRIMARY KEY,
    code VARCHAR(64),
    title VARCHAR(256) NOT NULL,
    description TEXT,
    discount_type VARCHAR(32) NOT NULL,
    discount_value FLOAT NOT NULL DEFAULT 0,
    min_spend FLOAT,
    max_discount FLOAT,
    merchant_id INTEGER NOT NULL REFERENCES merchants(id),
    category_id INTEGER REFERENCES categories(id),
    expires_at TIMESTAMP,
    source_url VARCHAR(1024),
    source_target VARCHAR(64) NOT NULL,
    scraped_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verified_at TIMESTAMP,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    quality_score INTEGER NOT NULL DEFAULT 0,
    view_count INTEGER NOT NULL DEFAULT 0,
    redeem_count INTEGER NOT NULL DEFAULT 0,
    region VARCHAR(32) NOT NULL DEFAULT 'national',
    content_hash VARCHAR(64) NOT NULL
);
CREATE INDEX ix_coupons_code ON coupons (code);
CREATE INDEX ix_coupons_merchant_id ON coupons (merchant_id);
CREATE INDEX ix_coupons_category_id ON coupons (category_id);
CREATE INDEX ix_coupons_source_target ON coupons (source_target);
CREATE INDEX ix_coupons_status ON coupons (status);
CREATE INDEX ix_coupons_content_hash ON coupons (content_hash);
CREATE INDEX ix_coupons_quality_score ON coupons (quality_score);
CREATE INDEX idx_merchant_status ON coupons (merchant_id, status);
CREATE INDEX idx_status_expires ON coupons (status, expires_at);
CREATE INDEX idx_region_status ON coupons (region, status);

CREATE TABLE scrape_logs (
    id SERIAL PRIMARY KEY,
    target_id VARCHAR(64) NOT NULL,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP,
    status VARCHAR(32) NOT NULL,
    items_found INTEGER NOT NULL DEFAULT 0,
    items_new INTEGER NOT NULL DEFAULT 0,
    items_updated INTEGER NOT NULL DEFAULT 0,
    error TEXT
);
CREATE INDEX ix_scrape_logs_target_id ON scrape_logs (target_id);

CREATE TABLE coupon_votes (
    id SERIAL PRIMARY KEY,
    coupon_id INTEGER NOT NULL REFERENCES coupons(id),
    value VARCHAR(16) NOT NULL,
    reporter_ip_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_coupon_votes_coupon_id ON coupon_votes (coupon_id);
CREATE INDEX ix_coupon_votes_reporter_ip_hash ON coupon_votes (reporter_ip_hash);
CREATE INDEX ix_coupon_votes_created_at ON coupon_votes (created_at);
CREATE INDEX idx_votes_coupon_value_time ON coupon_votes (coupon_id, value, created_at);
CREATE INDEX idx_votes_ip_coupon ON coupon_votes (reporter_ip_hash, coupon_id);

-- GIN trigram indexes for fuzzy search
CREATE INDEX ix_merchants_name_trgm ON merchants USING gin (lower(name) gin_trgm_ops);
CREATE INDEX ix_merchants_slug_trgm ON merchants USING gin (lower(slug) gin_trgm_ops);

-- Alembic version (mark as latest)
CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL PRIMARY KEY
);
INSERT INTO alembic_version (version_num) VALUES ('0002_quality_lifecycle');

-- ============================================================
-- DATA INSERTS
-- ============================================================
""")

    # ===== MERCHANTS =====
    parts.append("\n-- Merchants\n")
    for m in merchants:
        row = sql_row([
            m["id"], m["slug"], m["name"],
            m.get("logo_url"), m.get("website"),
        ])
        parts.append(f"INSERT INTO merchants (id, slug, name, logo_url, website) VALUES {row};\n")

    # ===== CATEGORIES =====
    parts.append("\n-- Categories\n")
    for c in categories:
        row = sql_row([c["id"], c["slug"], c["name"], c.get("icon")])
        parts.append(f"INSERT INTO categories (id, slug, name, icon) VALUES {row};\n")

    # ===== COUPONS =====
    parts.append("\n-- Coupons\n")
    cols = "id, code, title, description, discount_type, discount_value, min_spend, max_discount, merchant_id, category_id, expires_at, source_url, source_target, scraped_at, status, quality_score, view_count, redeem_count, region, content_hash"
    for c in coupons:
        merchant_id = c["merchant"]["id"] if c.get("merchant") else None
        category_id = c["category"]["id"] if c.get("category") else None
        # CouponOut may not include content_hash — fallback random
        content_hash = c.get("content_hash") or f"migrated-{c['id']}"
        row = sql_row([
            c["id"], c.get("code"), c["title"], c.get("description"),
            c["discount_type"], c.get("discount_value", 0),
            c.get("min_spend"), c.get("max_discount"),
            merchant_id, category_id,
            c.get("expires_at"), c.get("source_url"),
            c.get("source_target", "manual"),
            c.get("scraped_at"),
            c.get("status", "active"),
            c.get("quality_score", 0),
            c.get("view_count", 0),
            c.get("redeem_count", 0),
            c.get("region", "national"),
            content_hash,
        ])
        parts.append(f"INSERT INTO coupons ({cols}) VALUES {row};\n")

    # ===== SCRAPE_LOGS =====
    parts.append("\n-- Scrape logs (last 500)\n")
    for l in logs:
        row = sql_row([
            l["id"], l["target_id"], l["started_at"], l.get("finished_at"),
            l["status"], l.get("items_found", 0),
            l.get("items_new", 0), l.get("items_updated", 0),
            l.get("error"),
        ])
        parts.append(f"INSERT INTO scrape_logs (id, target_id, started_at, finished_at, status, items_found, items_new, items_updated, error) VALUES {row};\n")

    # ===== RESET SEQUENCES =====
    parts.append("""
-- ============================================================
-- Reset auto-increment sequences setelah manual ID inserts
-- ============================================================
SELECT setval(pg_get_serial_sequence('merchants', 'id'), COALESCE((SELECT MAX(id) FROM merchants), 1), true);
SELECT setval(pg_get_serial_sequence('categories', 'id'), COALESCE((SELECT MAX(id) FROM categories), 1), true);
SELECT setval(pg_get_serial_sequence('coupons', 'id'), COALESCE((SELECT MAX(id) FROM coupons), 1), true);
SELECT setval(pg_get_serial_sequence('scrape_logs', 'id'), COALESCE((SELECT MAX(id) FROM scrape_logs), 1), true);
SELECT setval(pg_get_serial_sequence('coupon_votes', 'id'), COALESCE((SELECT MAX(id) FROM coupon_votes), 1), true);

-- ============================================================
-- Sanity check counts
-- ============================================================
SELECT 'merchants' AS table_name, COUNT(*) AS rows FROM merchants
UNION ALL SELECT 'categories', COUNT(*) FROM categories
UNION ALL SELECT 'coupons', COUNT(*) FROM coupons
UNION ALL SELECT 'scrape_logs', COUNT(*) FROM scrape_logs
UNION ALL SELECT 'coupon_votes', COUNT(*) FROM coupon_votes;
""")

    sql_text = "".join(parts)
    OUT.write_text(sql_text, encoding="utf-8")

    print(f"\n✓ SQL file ditulis: {OUT}")
    print(f"  Total size: {len(sql_text):,} chars")
    print(f"  Total INSERT: {len(merchants) + len(categories) + len(coupons) + len(logs)} rows")
    print(f"\nNext: paste isi file ke Supabase Studio → SQL Editor → Run")


if __name__ == "__main__":
    main()
